### ISSUE TITLE
TypeError: object of type 'numpy.int64' has no len()

### ISSUE THREAD

**Issue by salsa360** [AutoViML/pandas_dq#2] opened 2023-04-07 11:55 UTC
Hi,

I get the following error with my data:
TypeError: object of type 'numpy.int64' has no len()

by running:

from pandas_dq import dq_report
dq_report(data, csv_engine="pandas", verbose=0)

Any suggestions as to what to do?

Thank you.

![pandas_dq issue with LAS file](https://user-images.githubusercontent.com/48823169/230604495-af70c0b4-dc35-4812-be19-16a31d7f6925.png)

**Comment by AutoViML** [comment] 2023-04-07 16:08
Hi @salsa360 :
Thanks for trying out pandas_dq. I have made some bug fixes already. Can you please upgrade and then check?
```
pip install pandas_dq --ignore-installed --no-cache-dir
```

If it still occurs, then please post a screen shot of the entire error output. I cannot tell right now where the error is.

Thanks
Auto Vimal team

**Comment by salsa360** [comment] 2023-04-08 03:24
Hi,

I've run the upgrade script you provided but the same problem is
encountered.

Attached is the screenshot of the error output.


Rgds
salsa360

**Comment by AutoViML** [comment] 2023-04-08 12:50
Sorry there is no screenshot attached. Can you upload it here via the zip file upload ?

**Comment by salsa360** [comment] 2023-04-08 14:10
My apologies, I must have omitted to insert it.  Here goes.

![pandas_dq issue with LAS file](https://user-images.githubusercontent.com/48823169/230725708-5cde6c95-2681-4a2b-a989-9a7717ff402f.png)

**Comment by eafpres** [comment] 2023-04-08 14:55
I ran into the same error.  Found that it is fine in Pandas 1.x but gives error in Pandas 2.0.0.  They changed a bunch of stuff related to numpy objects, which is likely the cause.

**Comment by salsa360** [comment] 2023-04-08 15:02
Hi Blaine,

Thanks for your feedback.

Will you be rolling back to Pandas 1?  Or get the Pandas 2.0.0 guys to
rectify the issue.


Regards
Kush

**Comment by eafpres** [comment] 2023-04-08 15:06
> Hi Blaine, Thanks for your feedback. Will you be rolling back to Pandas 1? Or get the Pandas 2.0.0 guys to rectify the issue. Regards Kush

It's not really an 'issue' for Pandas 2.0.0, it's due to them changing from numpy to Apache Arrow as the data backend; there appear to be cases where numpy objects are no longer acceptable to Pandas in some methods.  I think it will have to be addressed in each package with a Pandas dependency.  This is the second instance I've found already where Pandas 2.0.0 breaks something.

**Comment by AutoViML** [comment] 2023-04-09 11:31
Hi @salsa360 👍 Hope you can understand that pandas 2.0 is the one causing this problem and not pandas_dq.

@eafpres Blaine: thanks for pointing this out. 

I am closing this issue for now and will post a warning on README about pandas 2.0 

Thanks
Auto Vimal

**Closed as completed by AutoViML** 2023-04-09 11:31 UTC
